# Generated by Django 5.2.14 on 2026-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, max_length=64)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banners',
            },
        ),
    ]
